export type ErrorCode =
  | 'VALIDATION_ERROR'
  | 'AUTH_INVALID_CREDENTIALS'
  | 'AUTH_USER_BLOCKED'
  | 'AUTH_TOKEN_EXPIRED'
  | 'AUTH_TOKEN_INVALID'
  | 'FORBIDDEN_ROLE'
  | 'FORBIDDEN_OWNERSHIP'
  | 'INVALID_STATUS_TRANSITION'
  | 'TICKET_NOT_FOUND'
  | 'CUSTOMER_NOT_FOUND'
  | 'USER_NOT_FOUND'
  | 'INTERNAL_ERROR';

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_USER_BLOCKED: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_TOKEN_INVALID: 401,
  FORBIDDEN_ROLE: 403,
  FORBIDDEN_OWNERSHIP: 403,
  INVALID_STATUS_TRANSITION: 409,
  TICKET_NOT_FOUND: 404,
  CUSTOMER_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  INTERNAL_ERROR: 500,
};
